This is first test for jupyter.

In [1]:
import numpy as np

In [2]:
import pandas as ps

In [3]:
arr = np.array([0,1,2,3])

In [4]:
arr2 = 2 * arr

In [5]:
print(arr2)

[0 2 4 6]


In [6]:
len(arr)

4

In [7]:
arr.ndim

1

In [9]:
arr.min()


0

In [10]:
arr.max()

3

In [11]:
arr.shape

(4,)

In [12]:
matrix = np.array([[1,0],[0,1]])

In [13]:
matrix_2 = np.array([[2,3],[4,5]])

In [14]:
print(matrix)

[[1 0]
 [0 1]]


In [15]:
print(matrix_2)

[[2 3]
 [4 5]]


In [18]:
matrix.dot(matrix_2)

array([[ 4,  6],
       [ 8, 10]])

In [17]:
matrix = 2* matrix

In [19]:
matrix @ matrix_2

array([[ 4,  6],
       [ 8, 10]])